name: library_management_system
description: Library management system.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # State Management
  flutter_bloc: ^6.1.3
  # Value equality
  equatable: ^2.0.0
  # Functional programming
  dartz: ^0.9.2
  # Floor library for local storage
  floor: ^1.0.1
  # For OS-specific directory paths
  path_provider: ^2.0.1
  # Fetch data from API
  dio: ^3.0.10
  # Check the internet connection
  data_connection_checker: ^0.3.4
  # Service locator
  get_it: ^7.1.3
  # Rating bar
  flutter_rating_bar: ^4.0.0
  # Url launcher
  url_launcher: ^6.0.3
  bloc_test: ^7.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Floor library
  floor_generator: ^1.0.1
  build_runner:

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
